baseURL = "https://phrazao.github.io/ifi/"
title = "impossibilis"
theme = "blowfish"
colorScheme = "ocean"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
contentDir = "content"  # Define a pasta base para conteúdo
staticDir = "static"

# Ignora traduções do tema e usa apenas as do projeto
disableLanguages = ["pt-PT", "pt-BR"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    disabled = false
    languageCode = "en"
    contentDir = "content/en"  # Conteúdo em inglês
    [languages.en.params]
      logo = "/logo.svg"
      disableTextInHeader = true
      description = "Tabletop and card games producer and publisher."
      keywords = ["tabletop games", "board games", "card games", "impossibilis"]
      displayName = "EN"
      isoCode = "en"
      rtl = false
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        weight = 10
      [[languages.en.menu.main]]
        name = "Games"
        url = "/en/games/"
        weight = 20
      [[languages.en.menu.main]]
        name = "News"
        url = "/en/news/"
        weight = 30
      [[languages.en.menu.main]]
        name = "Contact"
        url = "/en/contact/"
        weight = 40

  [languages.pt]
    disabled = false
    languageCode = "pt"
    languageName = "Português"
    weight = 2
    contentDir = "content/pt"  # Conteúdo em português
    [languages.pt.params]
      logo = "/logo.svg"
      disableTextInHeader = true
      description = "Produtora e editora de jogos de tabuleiro e cartas."
      keywords = ["jogos de tabuleiro", "jogos de cartas", "impossibilis"]
      displayName = "PT"
      isoCode = "pt"
      rtl = false
      dateFormat = "2 January 2006"
    [languages.pt.menu]
      [[languages.pt.menu.main]]
        name = "Acerca"
        url = "/pt/about/"
        weight = 10
      [[languages.pt.menu.main]]
        name = "Jogos"
        url = "/pt/games/"
        weight = 20
      [[languages.pt.menu.main]]
        name = "Novidades"
        url = "/pt/news/"
        weight = 30
      [[languages.pt.menu.main]]
        name = "Contacto"
        url = "/pt/contact/"
        weight = 40
 
 [params]
  header.layout = "fixed-fill-blur"
  description = "impossibilis - Tabletop Games Producer and Publisher"
  defaultBackgroundImage = "background.jpeg"
  defaultFeaturedImage = "featured.jpeg"
  highlightCurrentMenuArea = true
  enableThemeToggle = true
  defaultTheme = "auto"
  autoSwitchAppearance = true
  showSearch = true
  favicon = "/favicon.ico"
  logo = "/logo.svg"
  disableTextInHeader = true
  showLanguageSwitcher = true
  customCSS = ["css/custom.css"]  # Adiciona o CSS personalizado
  author.name = "impossibilis"
  author.image = "simbolo.png"
  #author.image = "impossibilis-simbolo.svg"

  [params.homepage]
    #layout = "profile"
    layout = "background"
    #layout = "hero"
    #defaultBackgroundImage = "background.jpeg"
    #defaultFeaturedImage = "featured.jpeg"
    showRecent = true
    showRecentItems = 5
    showMoreLink = false
    showMoreLinkDest = "/posts/"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = false
    disableHeroImageFilter = false

  [params.footer]
    showCopyright = true
    showPowerBy = true
    showScrollToTop = true
    content = """
    © {{ now.Year }} impossibilis. Todos os direitos reservados.

    impossibilis, Lda
    Rua 16 de Março, 7 R/c Dir.
    2600-136 Vila Franca de XIRA
    Portugal

    NIF: 515548740

    Telefone Geral
    +351 961 819 241 (Chamada para a rede móvel nacional)

    [Informação Legal](/en/legal/) | [Termos e Condições](/en/terms/) | [Política de Privacidade](/en/privacy/) | [Política de Cookies](/en/cookies/)
    """
